apiVersion: v1
kind: Service
metadata:
  name: sample
spec:
  type: NodePort
  selector:
    app: sample
  ports:
  - name: web-interface
    protocol: TCP
    nodePort: 30100
    port: 80
    targetPort: 80