### namespaces
apiVersion: v1
kind: Namespace
metadata:
  name: devops-tools
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
##### Creating the volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-data
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
#### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops-tools
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        tooltype: jenkins
    spec:
      containers:
        - name: jenkins
          image: hippy96/jenkins:latest
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - mountPath: /var/run 
              name: docker-sock 
#      imagePullSecrets:
#        - name: regcred
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-data
        - name: docker-sock 
          hostPath: 
            path: /var/run 
---
### Services
kind: Service
apiVersion: v1
metadata:
  name: jenkins-ui
  namespace: devops-tools
  labels:
    tooltype: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: ui
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-discovery
  namespace: devops-tools
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
      name: slaves
---
### Service account, cluster role binding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-robot
  namespace: devops-tools
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins-robot
  namespace: devops-tools