FROM jenkins/jenkins

#COPY jenkins.yaml /usr/share/jenkins/ref/jenkins.yaml
ENV JAVA_OPTS "-Djenkins.install.runSetupWizard=false ${JAVA_OPTS:-}"
ENV JENKINS_HOME /var/jenkins_home
#ENV CASC_JENKINS_CONFIG /usr/share/jenkins/ref/
ENV DOCKERVERSION=18.03.1-ce
USER root
# Get docker cli
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz \
  && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 \
                 -C /usr/local/bin docker/docker \
  && rm docker-${DOCKERVERSION}.tgz

#CMD DOCKER_GID=$(stat -c '%g' /var/run/docker.sock) && \
#    groupadd -for -g ${DOCKER_GID} docker && \
#    usermod -aG docker jenkins && \
#    sudo -E -H -u jenkins bash -c /usr/local/bin/jenkins.sh

#RUN groupadd docker \
#  && usermod -aG docker jenkins \
#  && newgrp docker HAVE NOT TRIED THIS ONE YET

#USER jenkins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt