apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: hippy96/jenkins:latest
        volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
        ports:
        - containerPort: 8080
      volumes:
      - name: docker-socket
        hostPath:
            path: /var/run/docker.sock
      restartPolicy: Always
volumeMounts:
        - name: jenkins-home #this isn't persistent by itself so that needs to be looked at
          mountPath: /var/jenkins_home
    volumes:
      - name: jenkins-home
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
        name: jenkins-service
spec:
    type: LoadBalancer
    selector:
        app: jenkins
    ports:
        - name: jenkins-ui
          protocol: TCP
          port: 8080
          targetPort: 8080
        - name: remote-java-api
          protocol: TCP
          port: 50000
          targetPort: 50000