apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-robot
  namespace: devops-tools
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins-robot
  namespace: devops-tools